# Generated by Django 4.1.1 on 2022-09-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolistitem',
            name='pub_data',
            field=models.DateTimeField(),
        ),
    ]
