# Generated by Django 4.1.1 on 2022-09-29 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_alter_todolistitem_pub_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolistitem',
            name='pub_data',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 29, 15, 4, 45, 212243, tzinfo=datetime.timezone.utc)),
        ),
    ]
