# Generated by Django 4.1.1 on 2022-10-07 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_remove_todolistitem_content2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todolistitem',
            name='email',
        ),
    ]
