# Generated by Django 4.1.1 on 2022-10-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_remove_todolistitem_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolistitem',
            name='email',
            field=models.EmailField(default='noneEmain@gmail.com', max_length=30),
            preserve_default=False,
        ),
    ]
